import Head from "next/head";
import { ReactNode } from "react";

type LayoutProps = {
  title: string | undefined;
  children: ReactNode;
};

const Layout = ({ title, children }: LayoutProps) => {
  const titlePage = `${title} - Notes`;

  return (
    <>
      <Head>
        <title>{titlePage}</title>
        <meta name="description" content="Generated by Create Next Stack." />
      </Head>
      {children}
    </>
  );
};

export default Layout;
